#!/bin/bash
trap state ERR EXIT

function state() {
  exit $?
}

echo "Building containers"
docker compose build api

echo "Check for unused/dead code"
docker compose run api vulture app/ test/ whitelist.py

echo "Running tests"
docker compose run api pytest
